[package]
name = "hexroll3"
version = "0.1.0"
authors = ["Pen, Dice & Paper"]
description = "HEXROLL3 - the OSR sandbox generator"
license = "AGPL-3.0 OR Commercial"
repository = "https://github.com/hexroll/hexroll3"
homepage = "https://hexroll.app"
edition = "2021"

[dependencies]
